### ISSUE TITLE
Fails to build with gcc 5.3

### ISSUE THREAD

**Issue by MiRacLe-RPZ** [wadey/node-microtime#40]
```
$ npm install microtime
\
> microtime@0.3.3 install /home/miracle/tst/node_modules/microtime
> node-gyp rebuild

make: Entering directory '/home/miracle/tst/node_modules/microtime/build'
  CXX(target) Release/obj.target/microtime/src/microtime.o
../src/microtime.cc:10:32: error: ‘Arguments’ does not name a type
 static Handle<Value> Now(const Arguments &args) {
                                ^
In file included from ../src/microtime.cc:1:0:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h: In function ‘v8::Handle<v8::Value> Now(const int&)’:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/microtime.cc:11:17: error: within this context
     HandleScope scope;
                 ^
../src/microtime.cc:17:67: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
         return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                   ^
In file included from ../src/microtime.cc:2:0:
/home/miracle/.node-gyp/4.2.4/include/node/node.h:100:45: note: declared here
                 inline v8::Local<v8::Value> ErrnoException(
                                             ^
/home/miracle/.node-gyp/4.2.4/include/node/node.h:66:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
../src/microtime.cc:17:68: error: ‘ThrowException’ was not declared in this scope
         return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                    ^
../src/microtime.cc:20:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(Number::New((t.tv_sec * 1000000.0) + t.tv_usec));
                  ^
../src/microtime.cc:20:70: error: no matching function for call to ‘v8::Number::New(double)’
     return scope.Close(Number::New((t.tv_sec * 1000000.0) + t.tv_usec));
                                                                      ^
In file included from ../src/microtime.cc:1:0:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:2486:24: note: candidate: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:2486:24: note:   candidate expects 2 arguments, 1 provided
../src/microtime.cc: At global scope:
../src/microtime.cc:23:38: error: ‘Arguments’ does not name a type
 static Handle<Value> NowDouble(const Arguments &args) {
                                      ^
In file included from ../src/microtime.cc:1:0:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h: In function ‘v8::Handle<v8::Value> NowDouble(const int&)’:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/microtime.cc:24:17: error: within this context
     HandleScope scope;
                 ^
../src/microtime.cc:30:67: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
         return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                   ^
In file included from ../src/microtime.cc:2:0:
/home/miracle/.node-gyp/4.2.4/include/node/node.h:100:45: note: declared here
                 inline v8::Local<v8::Value> ErrnoException(
                                             ^
/home/miracle/.node-gyp/4.2.4/include/node/node.h:66:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
../src/microtime.cc:30:68: error: ‘ThrowException’ was not declared in this scope
         return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                    ^
../src/microtime.cc:33:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(Number::New(t.tv_sec + (t.tv_usec * 0.000001)));
                  ^
../src/microtime.cc:33:69: error: no matching function for call to ‘v8::Number::New(double)’
     return scope.Close(Number::New(t.tv_sec + (t.tv_usec * 0.000001)));
                                                                     ^
In file included from ../src/microtime.cc:1:0:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:2486:24: note: candidate: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:2486:24: note:   candidate expects 2 arguments, 1 provided
../src/microtime.cc: At global scope:
../src/microtime.cc:36:38: error: ‘Arguments’ does not name a type
 static Handle<Value> NowStruct(const Arguments &args) {
                                      ^
In file included from ../src/microtime.cc:1:0:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h: In function ‘v8::Handle<v8::Value> NowStruct(const int&)’:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/microtime.cc:37:17: error: within this context
     HandleScope scope;
                 ^
../src/microtime.cc:43:67: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
         return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                   ^
In file included from ../src/microtime.cc:2:0:
/home/miracle/.node-gyp/4.2.4/include/node/node.h:100:45: note: declared here
                 inline v8::Local<v8::Value> ErrnoException(
                                             ^
/home/miracle/.node-gyp/4.2.4/include/node/node.h:66:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
../src/microtime.cc:43:68: error: ‘ThrowException’ was not declared in this scope
         return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                    ^
../src/microtime.cc:46:38: error: invalid conversion from ‘int’ to ‘v8::Isolate*’ [-fpermissive]
     Local<Array> array = Array::New(2);
                                      ^
In file included from ../src/microtime.cc:1:0:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:2965:23: note:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../src/microtime.cc:47:30: error: no matching function for call to ‘v8::Integer::New(int)’
     array->Set(Integer::New(0), Uint32::New(t.tv_sec));
                              ^
In file included from ../src/microtime.cc:1:0:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:2499:25: note: candidate: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:2499:25: note:   candidate expects 2 arguments, 1 provided
../src/microtime.cc:47:53: error: no matching function for call to ‘v8::Uint32::New(__time_t&)’
     array->Set(Integer::New(0), Uint32::New(t.tv_sec));
                                                     ^
In file included from ../src/microtime.cc:1:0:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:2499:25: note: candidate: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:2499:25: note:   candidate expects 2 arguments, 1 provided
../src/microtime.cc:48:30: error: no matching function for call to ‘v8::Integer::New(int)’
     array->Set(Integer::New(1), Uint32::New(t.tv_usec));
                              ^
In file included from ../src/microtime.cc:1:0:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:2499:25: note: candidate: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:2499:25: note:   candidate expects 2 arguments, 1 provided
../src/microtime.cc:48:54: error: no matching function for call to ‘v8::Uint32::New(__suseconds_t&)’
     array->Set(Integer::New(1), Uint32::New(t.tv_usec));
                                                      ^
In file included from ../src/microtime.cc:1:0:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:2499:25: note: candidate: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:2499:25: note:   candidate expects 2 arguments, 1 provided
../src/microtime.cc:50:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(array);
                  ^
In file included from ../src/microtime.cc:1:0:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h: In function ‘void init(v8::Handle<v8::Object>)’:
/home/miracle/.node-gyp/4.2.4/include/node/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/microtime.cc:55:17: error: within this context
     HandleScope scope;
                 ^
../src/microtime.cc:57:39: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [4], v8::Handle<v8::Value> (&)(const int&))’
     NODE_SET_METHOD(target, "now", Now);
                                       ^
In file included from ../src/microtime.cc:2:0:
/home/miracle/.node-gyp/4.2.4/include/node/node.h:236:13: note: candidate: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/miracle/.node-gyp/4.2.4/include/node/node.h:236:13: note:   template argument deduction/substitution failed:
../src/microtime.cc:57:39: note:   cannot convert ‘Now’ (type ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’) to type ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’
     NODE_SET_METHOD(target, "now", Now);
                                       ^
../src/microtime.cc:58:51: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [10], v8::Handle<v8::Value> (&)(const int&))’
     NODE_SET_METHOD(target, "nowDouble", NowDouble);
                                                   ^
In file included from ../src/microtime.cc:2:0:
/home/miracle/.node-gyp/4.2.4/include/node/node.h:236:13: note: candidate: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/miracle/.node-gyp/4.2.4/include/node/node.h:236:13: note:   template argument deduction/substitution failed:
../src/microtime.cc:58:51: note:   cannot convert ‘NowDouble’ (type ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’) to type ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’
     NODE_SET_METHOD(target, "nowDouble", NowDouble);
                                                   ^
../src/microtime.cc:59:51: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [10], v8::Handle<v8::Value> (&)(const int&))’
     NODE_SET_METHOD(target, "nowStruct", NowStruct);
                                                   ^
In file included from ../src/microtime.cc:2:0:
/home/miracle/.node-gyp/4.2.4/include/node/node.h:236:13: note: candidate: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/miracle/.node-gyp/4.2.4/include/node/node.h:236:13: note:   template argument deduction/substitution failed:
../src/microtime.cc:59:51: note:   cannot convert ‘NowStruct’ (type ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’) to type ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’
     NODE_SET_METHOD(target, "nowStruct", NowStruct);
                                                   ^
microtime.target.mk:88: recipe for target 'Release/obj.target/microtime/src/microtime.o' failed
make: *** [Release/obj.target/microtime/src/microtime.o] Error 1
make: Leaving directory '/home/miracle/tst/node_modules/microtime/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.15
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/miracle/tst/node_modules/microtime
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.1.15
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "microtime"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! microtime@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the microtime@0.3.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/miracle/tst/npm-debug.log

```

**Comment by MiRacLe-RPZ** [comment]
Sorry, current version (2.0) build without problem
